import { notFound } from "next/navigation";
import Link from "next/link";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { PrintButton } from "@/components/print-button";
import type { ReportContent } from "@/lib/reports";

export default async function ReportDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const session = await auth();
  if (!session?.user) return null;

  const { id } = await params;

  const report = await db.report.findFirst({
    where: { id, workspaceId: session.user.workspaceId },
    include: { generatedBy: { select: { name: true } } },
  });

  if (!report) notFound();

  const content = report.contentJson as unknown as ReportContent;
  const { stats } = content;
  const negativePct =
    stats.totalItems > 0
      ? Math.round((stats.sentimentCounts.NEG / stats.totalItems) * 100)
      : 0;
  const previousTotal =
    stats.previousSentimentCounts.POS +
    stats.previousSentimentCounts.NEU +
    stats.previousSentimentCounts.NEG;
  const previousNegativePct =
    previousTotal > 0
      ? Math.round((stats.previousSentimentCounts.NEG / previousTotal) * 100)
      : null;

  return (
    <main className="mx-auto max-w-3xl px-6 py-8 print:max-w-full print:px-0">
      <div className="print:hidden mb-4 flex items-center justify-between">
        <Link href="/reports" className="text-sm text-ink-soft hover:text-ink-soft">
          ← All reports
        </Link>
        <PrintButton />
      </div>

      <article className="rounded-lg border border-line bg-paper-raised p-6 print:border-0 print:p-0 print:shadow-none">
        <h1 className="text-xl font-semibold text-ink">{report.title}</h1>
        <p className="mt-1 text-sm text-ink-soft">
          {new Date(report.periodStart).toLocaleDateString()} –{" "}
          {new Date(report.periodEnd).toLocaleDateString()} · generated by{" "}
          {report.generatedBy.name} on {new Date(report.createdAt).toLocaleDateString()}
        </p>

        <div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4">
          <Stat label="Total items" value={stats.totalItems} />
          <Stat
            label="Negative"
            value={`${negativePct}%`}
            sub={previousNegativePct !== null ? `was ${previousNegativePct}%` : undefined}
          />
          <Stat label="Positive" value={stats.sentimentCounts.POS} />
          <Stat label="Negative count" value={stats.sentimentCounts.NEG} />
        </div>

        <section className="mt-6">
          <h2 className="text-sm font-semibold uppercase tracking-wide text-ink-faint">
            Summary
          </h2>
          <p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-ink-soft">
            {content.narrative}
          </p>
        </section>

        {content.recommendedActions.length > 0 && (
          <section className="mt-6">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-ink-faint">
              Recommended actions
            </h2>
            <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-ink-soft">
              {content.recommendedActions.map((action, i) => (
                <li key={i}>{action}</li>
              ))}
            </ul>
          </section>
        )}

        {stats.topThemes.length > 0 && (
          <section className="mt-6">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-ink-faint">
              Top themes
            </h2>
            <ul className="mt-2 space-y-1">
              {stats.topThemes.map((t) => (
                <li key={t.name} className="flex items-center justify-between text-sm text-ink-soft">
                  <span className="flex items-center gap-2">
                    <span
                      className="h-2 w-2 rounded-full"
                      style={{ backgroundColor: t.color }}
                    />
                    {t.name}
                  </span>
                  <span className="text-ink-faint">{t.count} items</span>
                </li>
              ))}
            </ul>
          </section>
        )}

        {stats.representativeQuotes.length > 0 && (
          <section className="mt-6">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-ink-faint">
              Representative quotes
            </h2>
            <div className="mt-2 space-y-2">
              {stats.representativeQuotes.map((q, i) => (
                <blockquote
                  key={i}
                  className="rounded-md bg-paper p-3 text-sm italic text-ink-soft"
                >
                  "{q.content}"
                  <span className="mt-1 block text-xs not-italic text-ink-faint">
                    — {q.channel}, {q.sentiment ?? "unclassified"}
                  </span>
                </blockquote>
              ))}
            </div>
          </section>
        )}
      </article>
    </main>
  );
}

function Stat({ label, value, sub }: { label: string; value: string | number; sub?: string }) {
  return (
    <div className="rounded-lg bg-paper p-3 print:border print:border-line">
      <p className="text-xs text-ink-soft">{label}</p>
      <p className="mt-0.5 text-lg font-semibold text-ink">{value}</p>
      {sub && <p className="text-xs text-ink-faint">{sub}</p>}
    </div>
  );
}
